# fly.toml app configuration file generated for nextjs-websockets-patient-silence-2746 on 2025-07-17T18:17:58+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nextjs-websockets-patient-silence-2746'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
